
name: Pretty Nails Reusable CI

on: [workflow_call]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Dependencies
        run: |
          make create-env
          make install-dependencies
      
      - name: Run tests
        run: make test
